apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackcowmoo-prbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackcowmoo-prbot
  template:
    metadata:
      labels:
        app: blackcowmoo-prbot
    spec:
      containers:
        - image: blackcowmoo/prbot
          imagePullPolicy: Always
          name: blackcowmoo-prbot
          env:
            - name: GITHUB_USERNAME
              value: {{ .Values.prbot.github.username }}
            - name: GITHUB_PASSWORD
              value: {{ .Values.prbot.github.password }}
            - name: GITHUB_ORGANIZATION
              value: {{ .Values.prbot.github.organization }}
            - name: GITHUB_REPOSITORY
              value: {{ .Values.prbot.github.repository }}

---
apiVersion: v1
kind: Service
metadata:
  name: blackcowmoo-prbot
spec:
  selector:
    app: blackcowmoo-prbot
  ports:
    - name: webhook
      port: 3000
      targetPort: 3000
