// import { assert } from 'chai';
// import { requestAsync } from '../http';

// describe('Github webhook', () => {
//   it('Pull request', async () => {
//     const { status } = await requestAsync('POST', '/webhook', {
//       headers: {
//         'content-type': 'application/json',
//         'User-Agent': 'GitHub-Hookshot/03ed870',
//         'X-GitHub-Delivery': '93757d80-4c1b-11ea-9020-ab63927fb6dd',
//         'X-GitHub-Event': 'pull_request',
//       },
//       body: {
//         id: 8784012137,
//         sha: 'b34a923532dd79a1b7d32ea083d385ad03929fe3',
//         name: 'blackcowmoo/prbot',
//         target_url: 'https://travis-ci.org/blackcowmoo/prbot/builds/648464490?utm_source=github_status&utm_medium=notification',
//         avatar_url: 'https://avatars2.githubusercontent.com/oa/1508?v=4',
//         context: 'continuous-integration/travis-ci/pr',
//         description: 'The Travis CI build passed',
//         state: 'success',
//         commit: {
//           sha: 'b34a923532dd79a1b7d32ea083d385ad03929fe3',
//           node_id: 'MDY6Q29tbWl0MjM1OTkyNzk5OmIzNGE5MjM1MzJkZDc5YTFiN2QzMmVhMDgzZDM4NWFkMDM5MjlmZTM=',
//           commit: {
//             author: {
//               name: 'GyeongSu Han',
//               email: 'micalgenus@gmail.com',
//               date: '2020-02-10T15:38:11Z',
//             },
//             committer: {
//               name: 'GyeongSu Han',
//               email: 'micalgenus@gmail.com',
//               date: '2020-02-10T15:38:11Z',
//             },
//             message: 'Dummy probot',
//             tree: {
//               sha: '99d0fc509f7927b055b3977c7ec76170a1f95b6a',
//               url: 'https://api.github.com/repos/blackcowmoo/prbot/git/trees/99d0fc509f7927b055b3977c7ec76170a1f95b6a',
//             },
//             url: 'https://api.github.com/repos/blackcowmoo/prbot/git/commits/b34a923532dd79a1b7d32ea083d385ad03929fe3',
//             comment_count: 0,
//             verification: {
//               verified: false,
//               reason: 'unsigned',
//               signature: null,
//               payload: null,
//             },
//           },
//           url: 'https://api.github.com/repos/blackcowmoo/prbot/commits/b34a923532dd79a1b7d32ea083d385ad03929fe3',
//           html_url: 'https://github.com/blackcowmoo/prbot/commit/b34a923532dd79a1b7d32ea083d385ad03929fe3',
//           comments_url: 'https://api.github.com/repos/blackcowmoo/prbot/commits/b34a923532dd79a1b7d32ea083d385ad03929fe3/comments',
//           author: {
//             login: 'micalgenus',
//             id: 12954607,
//             node_id: 'MDQ6VXNlcjEyOTU0NjA3',
//             avatar_url: 'https://avatars3.githubusercontent.com/u/12954607?v=4',
//             gravatar_id: '',
//             url: 'https://api.github.com/users/micalgenus',
//             html_url: 'https://github.com/micalgenus',
//             followers_url: 'https://api.github.com/users/micalgenus/followers',
//             following_url: 'https://api.github.com/users/micalgenus/following{/other_user}',
//             gists_url: 'https://api.github.com/users/micalgenus/gists{/gist_id}',
//             starred_url: 'https://api.github.com/users/micalgenus/starred{/owner}{/repo}',
//             subscriptions_url: 'https://api.github.com/users/micalgenus/subscriptions',
//             organizations_url: 'https://api.github.com/users/micalgenus/orgs',
//             repos_url: 'https://api.github.com/users/micalgenus/repos',
//             events_url: 'https://api.github.com/users/micalgenus/events{/privacy}',
//             received_events_url: 'https://api.github.com/users/micalgenus/received_events',
//             type: 'User',
//             site_admin: false,
//           },
//           committer: {
//             login: 'micalgenus',
//             id: 12954607,
//             node_id: 'MDQ6VXNlcjEyOTU0NjA3',
//             avatar_url: 'https://avatars3.githubusercontent.com/u/12954607?v=4',
//             gravatar_id: '',
//             url: 'https://api.github.com/users/micalgenus',
//             html_url: 'https://github.com/micalgenus',
//             followers_url: 'https://api.github.com/users/micalgenus/followers',
//             following_url: 'https://api.github.com/users/micalgenus/following{/other_user}',
//             gists_url: 'https://api.github.com/users/micalgenus/gists{/gist_id}',
//             starred_url: 'https://api.github.com/users/micalgenus/starred{/owner}{/repo}',
//             subscriptions_url: 'https://api.github.com/users/micalgenus/subscriptions',
//             organizations_url: 'https://api.github.com/users/micalgenus/orgs',
//             repos_url: 'https://api.github.com/users/micalgenus/repos',
//             events_url: 'https://api.github.com/users/micalgenus/events{/privacy}',
//             received_events_url: 'https://api.github.com/users/micalgenus/received_events',
//             type: 'User',
//             site_admin: false,
//           },
//           parents: [
//             {
//               sha: 'd92882004061e0178bc30a7013e8ddcc5ca80b9e',
//               url: 'https://api.github.com/repos/blackcowmoo/prbot/commits/d92882004061e0178bc30a7013e8ddcc5ca80b9e',
//               html_url: 'https://github.com/blackcowmoo/prbot/commit/d92882004061e0178bc30a7013e8ddcc5ca80b9e',
//             },
//           ],
//         },
//         branches: [
//           {
//             name: 'feature/initialize-probot',
//             commit: {
//               sha: 'b34a923532dd79a1b7d32ea083d385ad03929fe3',
//               url: 'https://api.github.com/repos/blackcowmoo/prbot/commits/b34a923532dd79a1b7d32ea083d385ad03929fe3',
//             },
//             protected: false,
//           },
//         ],
//         created_at: '2020-02-10T15:42:23+00:00',
//         updated_at: '2020-02-10T15:42:23+00:00',
//         repository: {
//           id: 235992799,
//           node_id: 'MDEwOlJlcG9zaXRvcnkyMzU5OTI3OTk=',
//           name: 'prbot',
//           full_name: 'blackcowmoo/prbot',
//           private: false,
//           owner: {
//             login: 'blackcowmoo',
//             id: 60027029,
//             node_id: 'MDEyOk9yZ2FuaXphdGlvbjYwMDI3MDI5',
//             avatar_url: 'https://avatars1.githubusercontent.com/u/60027029?v=4',
//             gravatar_id: '',
//             url: 'https://api.github.com/users/blackcowmoo',
//             html_url: 'https://github.com/blackcowmoo',
//             followers_url: 'https://api.github.com/users/blackcowmoo/followers',
//             following_url: 'https://api.github.com/users/blackcowmoo/following{/other_user}',
//             gists_url: 'https://api.github.com/users/blackcowmoo/gists{/gist_id}',
//             starred_url: 'https://api.github.com/users/blackcowmoo/starred{/owner}{/repo}',
//             subscriptions_url: 'https://api.github.com/users/blackcowmoo/subscriptions',
//             organizations_url: 'https://api.github.com/users/blackcowmoo/orgs',
//             repos_url: 'https://api.github.com/users/blackcowmoo/repos',
//             events_url: 'https://api.github.com/users/blackcowmoo/events{/privacy}',
//             received_events_url: 'https://api.github.com/users/blackcowmoo/received_events',
//             type: 'Organization',
//             site_admin: false,
//           },
//           html_url: 'https://github.com/blackcowmoo/prbot',
//           description: null,
//           fork: false,
//           url: 'https://api.github.com/repos/blackcowmoo/prbot',
//           forks_url: 'https://api.github.com/repos/blackcowmoo/prbot/forks',
//           keys_url: 'https://api.github.com/repos/blackcowmoo/prbot/keys{/key_id}',
//           collaborators_url: 'https://api.github.com/repos/blackcowmoo/prbot/collaborators{/collaborator}',
//           teams_url: 'https://api.github.com/repos/blackcowmoo/prbot/teams',
//           hooks_url: 'https://api.github.com/repos/blackcowmoo/prbot/hooks',
//           issue_events_url: 'https://api.github.com/repos/blackcowmoo/prbot/issues/events{/number}',
//           events_url: 'https://api.github.com/repos/blackcowmoo/prbot/events',
//           assignees_url: 'https://api.github.com/repos/blackcowmoo/prbot/assignees{/user}',
//           branches_url: 'https://api.github.com/repos/blackcowmoo/prbot/branches{/branch}',
//           tags_url: 'https://api.github.com/repos/blackcowmoo/prbot/tags',
//           blobs_url: 'https://api.github.com/repos/blackcowmoo/prbot/git/blobs{/sha}',
//           git_tags_url: 'https://api.github.com/repos/blackcowmoo/prbot/git/tags{/sha}',
//           git_refs_url: 'https://api.github.com/repos/blackcowmoo/prbot/git/refs{/sha}',
//           trees_url: 'https://api.github.com/repos/blackcowmoo/prbot/git/trees{/sha}',
//           statuses_url: 'https://api.github.com/repos/blackcowmoo/prbot/statuses/{sha}',
//           languages_url: 'https://api.github.com/repos/blackcowmoo/prbot/languages',
//           stargazers_url: 'https://api.github.com/repos/blackcowmoo/prbot/stargazers',
//           contributors_url: 'https://api.github.com/repos/blackcowmoo/prbot/contributors',
//           subscribers_url: 'https://api.github.com/repos/blackcowmoo/prbot/subscribers',
//           subscription_url: 'https://api.github.com/repos/blackcowmoo/prbot/subscription',
//           commits_url: 'https://api.github.com/repos/blackcowmoo/prbot/commits{/sha}',
//           git_commits_url: 'https://api.github.com/repos/blackcowmoo/prbot/git/commits{/sha}',
//           comments_url: 'https://api.github.com/repos/blackcowmoo/prbot/comments{/number}',
//           issue_comment_url: 'https://api.github.com/repos/blackcowmoo/prbot/issues/comments{/number}',
//           contents_url: 'https://api.github.com/repos/blackcowmoo/prbot/contents/{+path}',
//           compare_url: 'https://api.github.com/repos/blackcowmoo/prbot/compare/{base}...{head}',
//           merges_url: 'https://api.github.com/repos/blackcowmoo/prbot/merges',
//           archive_url: 'https://api.github.com/repos/blackcowmoo/prbot/{archive_format}{/ref}',
//           downloads_url: 'https://api.github.com/repos/blackcowmoo/prbot/downloads',
//           issues_url: 'https://api.github.com/repos/blackcowmoo/prbot/issues{/number}',
//           pulls_url: 'https://api.github.com/repos/blackcowmoo/prbot/pulls{/number}',
//           milestones_url: 'https://api.github.com/repos/blackcowmoo/prbot/milestones{/number}',
//           notifications_url: 'https://api.github.com/repos/blackcowmoo/prbot/notifications{?since,all,participating}',
//           labels_url: 'https://api.github.com/repos/blackcowmoo/prbot/labels{/name}',
//           releases_url: 'https://api.github.com/repos/blackcowmoo/prbot/releases{/id}',
//           deployments_url: 'https://api.github.com/repos/blackcowmoo/prbot/deployments',
//           created_at: '2020-01-24T11:44:48Z',
//           updated_at: '2020-02-10T15:17:25Z',
//           pushed_at: '2020-02-10T15:39:51Z',
//           git_url: 'git://github.com/blackcowmoo/prbot.git',
//           ssh_url: 'git@github.com:blackcowmoo/prbot.git',
//           clone_url: 'https://github.com/blackcowmoo/prbot.git',
//           svn_url: 'https://github.com/blackcowmoo/prbot',
//           homepage: null,
//           size: 246,
//           stargazers_count: 0,
//           watchers_count: 0,
//           language: 'TypeScript',
//           has_issues: true,
//           has_projects: true,
//           has_downloads: true,
//           has_wiki: true,
//           has_pages: false,
//           forks_count: 0,
//           mirror_url: null,
//           archived: false,
//           disabled: false,
//           open_issues_count: 1,
//           license: {
//             key: 'mit',
//             name: 'MIT License',
//             spdx_id: 'MIT',
//             url: 'https://api.github.com/licenses/mit',
//             node_id: 'MDc6TGljZW5zZTEz',
//           },
//           forks: 0,
//           open_issues: 1,
//           watchers: 0,
//           default_branch: 'master',
//         },
//         organization: {
//           login: 'blackcowmoo',
//           id: 60027029,
//           node_id: 'MDEyOk9yZ2FuaXphdGlvbjYwMDI3MDI5',
//           url: 'https://api.github.com/orgs/blackcowmoo',
//           repos_url: 'https://api.github.com/orgs/blackcowmoo/repos',
//           events_url: 'https://api.github.com/orgs/blackcowmoo/events',
//           hooks_url: 'https://api.github.com/orgs/blackcowmoo/hooks',
//           issues_url: 'https://api.github.com/orgs/blackcowmoo/issues',
//           members_url: 'https://api.github.com/orgs/blackcowmoo/members{/member}',
//           public_members_url: 'https://api.github.com/orgs/blackcowmoo/public_members{/member}',
//           avatar_url: 'https://avatars1.githubusercontent.com/u/60027029?v=4',
//           description: null,
//         },
//         sender: {
//           login: 'micalgenus',
//           id: 12954607,
//           node_id: 'MDQ6VXNlcjEyOTU0NjA3',
//           avatar_url: 'https://avatars3.githubusercontent.com/u/12954607?v=4',
//           gravatar_id: '',
//           url: 'https://api.github.com/users/micalgenus',
//           html_url: 'https://github.com/micalgenus',
//           followers_url: 'https://api.github.com/users/micalgenus/followers',
//           following_url: 'https://api.github.com/users/micalgenus/following{/other_user}',
//           gists_url: 'https://api.github.com/users/micalgenus/gists{/gist_id}',
//           starred_url: 'https://api.github.com/users/micalgenus/starred{/owner}{/repo}',
//           subscriptions_url: 'https://api.github.com/users/micalgenus/subscriptions',
//           organizations_url: 'https://api.github.com/users/micalgenus/orgs',
//           repos_url: 'https://api.github.com/users/micalgenus/repos',
//           events_url: 'https://api.github.com/users/micalgenus/events{/privacy}',
//           received_events_url: 'https://api.github.com/users/micalgenus/received_events',
//           type: 'User',
//           site_admin: false,
//         },
//       },
//     });

//     assert.equal(status, 200);
//   });
// });
